### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by matheus-rodrigues00** [victorfernandesraton/victorfernandesraton.github.io#21]
I'm not really sure how to run the project, what do you think 'bout creating a README.md? @victorfernandesraton

**Comment by victorfernandesraton** [comment]
Sorry for not noticing this, the project in question was generated by Hugo's CLI, so it doesn't have any helpers.

**Comment by victorfernandesraton** [comment]
Create this PR https://github.com/victorfernandesraton/victorfernandesraton.github.io/pull/22 to solve this issue

**Comment by victorfernandesraton** [comment]
This issue has been close by https://github.com/victorfernandesraton/victorfernandesraton.github.io/pull/22

**Comment by victorfernandesraton** [comment]
This issue has been closed by https://github.com/victorfernandesraton/victorfernandesraton.github.io/pull/22
